### ISSUE TITLE
GPIO29 Pin on Joystick not working

### ISSUE THREAD

**Issue by SBeyer6** [OpenStickCommunity/GP2040-CE#1056]
### Expected Behavior

Y-axis of right analog stick to move up and down based on user input.

### Current Behavior

No response on Y-axis.

### Context

Currently running firmware version 0.7.9 (GP2040-CE_0.7.9_Pico.uf2). Currently running on Raspberry Pi Pico, part number is A135P (link: https://www.amazon.com.au/dp/B09KTNF5XR?ref=ppx_yo2ov_dt_b_product_details&th=1). The joystick model number is COM-09032.  Wiring diagram for setup included below.

I've tested the joystick on pins 26 and 27 and had no issues. I wish to use GP29 since I require dual joysticks for my setup. The same 3v3 and gnd pins are being used for both analog sticks.

Upon doing some research into using pin 29 on the Pico I found that I had to use the VSYS pin. I'm unsure if I need to make modifications to the pico, or if another rp2040 will have to be used.

### Steps to Reproduce

1. Connect wiring to match provided diagram.
2. Install GP2040-ce firmware.
3. Apply pin configuration for analog (as shown below).
4. Reboot in controller mode.
5. Open gamepad tester.
6. See that x-axis for right analog works but not y-axis.

### Screenshots & Files
Wiring Diagram:
![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/51429184/30dd1a9a-3993-43e5-98b5-935530213cf8)
Current Analog Pin configuration:
![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/51429184/b144106e-de3a-4048-9870-0b07780f403c)

If there's other information you need please let me know, thanks in advance!

**Comment by arntsonl** [comment]
The problem here is you can't use Pin 29 on the Pico. You'll need either an embedded board with pin 29 exposed or do some desoldering on the Pico itself which is way out of the scope of this project.

I would suggest getting ahold of an advanced breakout board from Train through either SGF or another vendor such as this: https://sgfdevices.com/products/sgf-gp2040-ce-advanced-breakout-board-pe which gives you access to Pin 29.

For additional information for the Pico, please refer to https://datasheets.raspberrypi.com/pico/pico-datasheet.pdf
