### ISSUE TITLE
When pressing the right + DDI right keys at the same time, is it possible to clear the previous key?

### ISSUE THREAD

**Issue by h-chwn** [OpenStickCommunity/GP2040-CE#993]
> Please read these quoted sections before submitting, and remove them (including this one) when you have provided what
> is asked, in order to make addressing the issue easier for everyone. Thank you!
>
> Be sure to:
> * Check the documentation [HERE](https://gp2040-ce.info/) to answer many questions on firmware capabilities and usage.
> * Make sure that your idea has not already been filed [HERE](https://github.com/OpenStickCommunity/GP2040-CE/issues).
> * Confirm the feature does not exist in the latest version of the firmware, found
  [HERE](https://github.com/OpenStickCommunity/GP2040-CE/releases).

### Problem

**> Which problem is this feature request solving?**
I'm trying to use GAFRO mode in Tekken8.
For example, for 66RP, you must completely release the Right key of the previous input and then press the DDI Right key for 66 for normal operation.
Are there any features that make it more convenient to use?

### Solution

**> Describe the solution you would like to see**
When Right + DDI right key press, separates the signals of the previous input and the current input. like Last Win.

**### Do you plan to work on this feature yourself?**
If it is possible to add features, please make a request.
If not, please give me tips on how to edit the source.

**Comment by bsstephan** [comment]
> When Right + DDI right key press, separates the signals of the previous input and the current input. like Last Win.

I do not foresee us using SOCD cleaning in this way. For starters, Right + DDI Right is not an opposite cardinal direction, so it seems like a confusing user expectation in general. Additionally, we do not introduce input assistance features (outside of macros) for a variety of reasons, so we would not add a feature that added one Neutral frame.

However, there may be a solution in the firmware. Is there a reason you are trying to solve this with Right + DDI Right? The "Reverse Input" addon can also neutralize a direction, so that you could do Right = 6, Right + Reverse (Neutral) = 5, Right = 6. Then you would hold Right and just tap Reverse Input.

**Comment by h-chwn** [comment]
@bsstephan
I found that the feature I wanted was a new add-on.
Thank you for your reply.
